<?php
require_once __DIR__ . '/includes/functions.php'; require_admin();
if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    verify_csrf(); $action = $_POST['action'] ?? '';
    try {
        if (in_array($action, ['save_income', 'save_expense'], true)) {
            $store = $action === 'save_income' ? 'income' : 'expenses'; $entry = transaction_input($store); $id = $_POST['id'] ?? '';
            update_json($store, function (&$rows) use ($entry, $id) { if ($id) { foreach ($rows as &$row) if (($row['id'] ?? '') === $id) { $row = array_merge($row, $entry, ['updated_at' => date('c')]); return; } throw new InvalidArgumentException('Record was not found.'); } $rows[] = array_merge($entry, ['id' => bin2hex(random_bytes(12)), 'created_at' => date('c')]); });
            flash('success', ucfirst(rtrim($store, 's')) . ' record saved.');
        } elseif (in_array($action, ['delete_income', 'delete_expense'], true)) {
            $store = $action === 'delete_income' ? 'income' : 'expenses'; $id = $_POST['id'] ?? '';
            update_json($store, function (&$rows) use ($id) { $rows = array_values(array_filter($rows, fn($r) => ($r['id'] ?? '') !== $id)); }); flash('success', 'Record deleted.');
        } elseif ($action === 'create_user') {
            $name = trim($_POST['name'] ?? ''); $email = strtolower(trim($_POST['email'] ?? '')); $password = $_POST['password'] ?? ''; $role = $_POST['role'] ?? 'user';
            if (mb_strlen($name) < 2 || !filter_var($email, FILTER_VALIDATE_EMAIL) || strlen($password) < 8 || !in_array($role, ['user','admin'], true)) throw new InvalidArgumentException('Enter a valid name, email, role, and 8-character password.');
            update_json('users', function (&$users) use ($name,$email,$password,$role) { foreach($users as $u) if(strcasecmp($u['email'],$email)===0) throw new InvalidArgumentException('Email already exists.'); $users[]=['id'=>bin2hex(random_bytes(12)),'name'=>mb_substr($name,0,80),'email'=>$email,'password'=>password_hash($password,PASSWORD_DEFAULT),'role'=>$role,'created_at'=>date('c')]; }); flash('success', 'User created.');
        } elseif ($action === 'reset_password') {
            $id = $_POST['id'] ?? ''; $password = $_POST['password'] ?? ''; if(strlen($password)<8) throw new InvalidArgumentException('Password must be at least 8 characters.');
            update_json('users', function (&$users) use ($id,$password) { foreach($users as &$u) if($u['id']===$id){$u['password']=password_hash($password,PASSWORD_DEFAULT); return;} throw new InvalidArgumentException('User not found.'); }); flash('success', 'Password reset.');
        } elseif ($action === 'delete_user') {
            $id = $_POST['id'] ?? ''; if($id === current_user()['id']) throw new InvalidArgumentException('You cannot delete your own account.'); update_json('users', function (&$users) use($id){$users=array_values(array_filter($users,fn($u)=>$u['id']!==$id));}); flash('success','User deleted.');
        }
    } catch (InvalidArgumentException $e) { flash('error', $e->getMessage()); }
    redirect('admin.php');
}
$income=read_json('income'); $expenses=read_json('expenses'); $users=read_json('users'); usort($income,fn($a,$b)=>strcmp($b['date'],$a['date'])); usort($expenses,fn($a,$b)=>strcmp($b['date'],$a['date'])); $pageTitle='Manage accounting'; require __DIR__.'/includes/header.php';
?>
<?= show_flash() ?><div class="admin-actions"><button class="primary" onclick="openTransaction('income')">+ Add income</button><button class="primary" onclick="openTransaction('expenses')">+ Add expense</button><button class="secondary" onclick="openModal('user-modal')">+ Create user</button></div>
<div class="admin-section"><h2>Income records</h2><div class="table-card"><div class="table-scroll"><table><thead><tr><th>Date</th><th>Sender</th><th>Amount</th><th>Currency</th><th>Reason</th><th></th></tr></thead><tbody><?php foreach($income as $r): ?><tr><td><?=e($r['date'])?></td><td><?=e($r['party'])?></td><td><?=money((float)$r['amount'])?></td><td><?=e($r['currency'])?></td><td><?=e($r['reason'])?></td><td class="actions"><button onclick='editTransaction(<?= json_encode($r, JSON_HEX_APOS|JSON_HEX_QUOT) ?>,"income")'>Edit</button><form method="post" onsubmit="return confirm('Delete this record?')"><?=csrf_input()?><input type="hidden" name="action" value="delete_income"><input type="hidden" name="id" value="<?=e($r['id'])?>"><button class="danger">Delete</button></form></td></tr><?php endforeach; ?><?php if(!$income):?><tr><td colspan="6" class="empty">No income records.</td></tr><?php endif;?></tbody></table></div></div></div>
<div class="admin-section"><h2>Expense records</h2><div class="table-card"><div class="table-scroll"><table><thead><tr><th>Date</th><th>Paid to</th><th>Amount</th><th>Currency</th><th>Reason</th><th></th></tr></thead><tbody><?php foreach($expenses as $r): ?><tr><td><?=e($r['date'])?></td><td><?=e($r['party'])?></td><td><?=money((float)$r['amount'])?></td><td><?=e($r['currency'])?></td><td><?=e($r['reason'])?></td><td class="actions"><button onclick='editTransaction(<?= json_encode($r, JSON_HEX_APOS|JSON_HEX_QUOT) ?>,"expenses")'>Edit</button><form method="post" onsubmit="return confirm('Delete this record?')"><?=csrf_input()?><input type="hidden" name="action" value="delete_expense"><input type="hidden" name="id" value="<?=e($r['id'])?>"><button class="danger">Delete</button></form></td></tr><?php endforeach; ?><?php if(!$expenses):?><tr><td colspan="6" class="empty">No expense records.</td></tr><?php endif;?></tbody></table></div></div></div>
<div class="admin-section"><h2>Users</h2><div class="table-card"><div class="table-scroll"><table><thead><tr><th>Name</th><th>Email</th><th>Role</th><th>Created</th><th></th></tr></thead><tbody><?php foreach($users as $u):?><tr><td><?=e($u['name'])?></td><td><?=e($u['email'])?></td><td><span class="badge"><?=e($u['role'])?></span></td><td><?=e(substr($u['created_at'],0,10))?></td><td class="actions"><button onclick="resetUser('<?=e($u['id'])?>','<?=e($u['name'])?>')">Reset password</button><?php if($u['id']!==current_user()['id']):?><form method="post" onsubmit="return confirm('Delete this user?')"><?=csrf_input()?><input type="hidden" name="action" value="delete_user"><input type="hidden" name="id" value="<?=e($u['id'])?>"><button class="danger">Delete</button></form><?php endif;?></td></tr><?php endforeach;?></tbody></table></div></div></div>
<div class="modal" id="transaction-modal"><div class="modal-card"><button class="close" onclick="closeModal('transaction-modal')">×</button><h2 id="transaction-title">Add record</h2><form method="post" id="transaction-form"><?=csrf_input()?><input type="hidden" name="action" id="transaction-action"><input type="hidden" name="id" id="transaction-id"><label>Date<input type="date" name="date" id="t-date" required></label><label id="party-label">Sender<input type="text" name="party" id="t-party" required maxlength="120"></label><label>Amount<input type="number" name="amount" id="t-amount" required min="0.01" step="0.01"></label><label>Currency<input type="text" name="currency" id="t-currency" required value="USD" maxlength="10" pattern="[A-Za-z]{3,10}"></label><label>Reason / Description<textarea name="reason" id="t-reason" required maxlength="500"></textarea></label><button class="primary">Save record</button></form></div></div>
<div class="modal" id="user-modal"><div class="modal-card"><button class="close" onclick="closeModal('user-modal')">×</button><h2>Create user</h2><form method="post"><?=csrf_input()?><input type="hidden" name="action" value="create_user"><label>Name<input name="name" required maxlength="80"></label><label>Email<input type="email" name="email" required></label><label>Role<select name="role"><option value="user">User (view only)</option><option value="admin">Administrator</option></select></label><label>Password<input type="password" name="password" required minlength="8"></label><button class="primary">Create user</button></form></div></div>
<div class="modal" id="reset-modal"><div class="modal-card"><button class="close" onclick="closeModal('reset-modal')">×</button><h2>Reset password</h2><form method="post"><?=csrf_input()?><input type="hidden" name="action" value="reset_password"><input type="hidden" name="id" id="reset-id"><p id="reset-name"></p><label>New password<input type="password" name="password" required minlength="8"></label><button class="primary">Reset password</button></form></div></div>
<?php require __DIR__.'/includes/footer.php'; ?>
