<?php
require_once __DIR__ . '/includes/functions.php'; require_login();
$income = read_json('income'); $expenses = read_json('expenses');
$search = trim($_GET['search'] ?? ''); $date = trim($_GET['date'] ?? '');
$filter = function(array $row) use ($search, $date): bool { $haystack = strtolower(implode(' ', [$row['party'], $row['currency'], $row['reason']])); return ($search === '' || str_contains($haystack, strtolower($search))) && ($date === '' || $row['date'] === $date); };
$income = array_values(array_filter($income, $filter)); $expenses = array_values(array_filter($expenses, $filter));
usort($income, fn($a,$b) => strcmp($b['date'], $a['date'])); usort($expenses, fn($a,$b) => strcmp($b['date'], $a['date'])); $stats = totals();
$pageTitle = is_admin() ? 'Accounting overview' : 'My accounting records'; require __DIR__ . '/includes/header.php';
?>
<?= show_flash() ?><div class="stats"><div class="stat income"><span>Total income</span><strong><?= money($stats['income']) ?></strong></div><div class="stat expense"><span>Total expenses</span><strong><?= money($stats['expenses']) ?></strong></div><div class="stat balance"><span>Current balance</span><strong><?= money($stats['balance']) ?></strong></div><div class="stat"><span>Transactions</span><strong><?= $stats['transactions'] ?></strong></div></div>
<form class="filters" method="get"><input type="search" name="search" placeholder="Search sender, reason, currency…" value="<?= e($search) ?>"><input type="date" name="date" value="<?= e($date) ?>"><button class="secondary">Filter</button><a href="dashboard.php">Clear</a></form>
<div class="tables-grid"><section class="table-card"><div class="table-heading"><h2>Income</h2><span><?= count($income) ?> records</span></div><div class="table-scroll"><table><thead><tr><th>Date</th><th>Sender / From</th><th>Amount</th><th>Currency</th><th>Reason / Description</th></tr></thead><tbody><?php foreach($income as $r): ?><tr><td><?= e($r['date']) ?></td><td><?= e($r['party']) ?></td><td><?= money((float)$r['amount']) ?></td><td><?= e($r['currency']) ?></td><td><?= e($r['reason']) ?></td></tr><?php endforeach; ?><?php if(!$income): ?><tr><td colspan="5" class="empty">No income records found.</td></tr><?php endif; ?></tbody></table></div></section><section class="table-card"><div class="table-heading"><h2>Expenses</h2><span><?= count($expenses) ?> records</span></div><div class="table-scroll"><table><thead><tr><th>Date</th><th>Paid to</th><th>Amount</th><th>Currency</th><th>Reason / Description</th></tr></thead><tbody><?php foreach($expenses as $r): ?><tr><td><?= e($r['date']) ?></td><td><?= e($r['party']) ?></td><td><?= money((float)$r['amount']) ?></td><td><?= e($r['currency']) ?></td><td><?= e($r['reason']) ?></td></tr><?php endforeach; ?><?php if(!$expenses): ?><tr><td colspan="5" class="empty">No expense records found.</td></tr><?php endif; ?></tbody></table></div></section></div>
<?php require __DIR__ . '/includes/footer.php'; ?>
